#!/bin/sh

echo "Running Laravel tests..."

./vendor/bin/pest

if [ $? -ne 0 ]
  echo "Tests failed. Commit aborted."
  exit 1
fi

echo "All tests passed. Proceeding with commit."
exit 0


FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.php$')

if [ -z "$FILES" ]; then
    exit 0
fi

./vendor/bin/pint $FILES

git add $FILES

exit 0
